service: serverless

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  getArticle:
    handler: article/article.get
    events:
      - http:
          path: article/get/{canonical}
          method: get
          cors: true
          authorizer: false
  searchArticle:
    handler: article/article.search
    events:
      - http:
          path: article/search/{title}
          method: get
          cors: true
          authorizer: false
  getJournalist:
    handler: journalist/journalist.get
    events:
      - http:
          path: journalist/get/{name}
          method: get
          cors: true
          authorizer: false
  searchJournalist:
    handler: journalist/journalist.search
    events:
      - http:
          path: journalist/search/{name}
          method: get
          cors: true
          authorizer: false