service: serverless

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1
  timeout: 90 

functions:
  # ARTICLES SECCION
  getArticles:
    handler: article/article.get
    timeout: 60
    events:
      - http:
          path: article/all
          method: get
          cors: true
          authorizer: false
  showArticle:
    handler: article/article.show
    timeout: 60
    events:
      - http:
          path: article/show/{articleId}
          method: get
          cors: true
          authorizer: false
  showFullArticle:
    handler: article/article.getFullArticle
    timeout: 60
    events:
      - http:
          path: article/showFull/{articleId}
          method: get
          cors: true
          authorizer: false
  showArticleContent:
    handler: article/article.getArticleContent
    timeout: 60
    events:
      - http:
          path: article/content/{articleId}
          method: get
          cors: true
          authorizer: false
  getByCanonical:
    handler: article/article.getByCanonical
    timeout: 60
    events:
      - http:
          path: article/canonical/{canonical}
          method: get
          cors: true
          authorizer: false
  getArticlesByCategory:
      handler: article/article.getByCategory
      timeout: 60
      events:
        - http:
            path: article/category/{categoryId}
            method: get
            cors: true
            authorizer: false
  getArticlesByAuthor:
      handler: article/article.getByAuthor
      timeout: 60
      events:
        - http:
            path: article/author/{authorId}
            method: get
            cors: true
            authorizer: false
  searchArticles:
      handler: article/article.search
      timeout: 60
      events:
        - http:
            path: article/search/{criteria}
            method: get
            cors: true
            authorizer: false
# AUTHOR SECCION
  getAuthors:
    handler: author/author.get
    timeout: 60
    events:
      - http:
          path: author/all
          method: get
          cors: true
          authorizer: false
  showAuthor:
    handler: author/author.show
    timeout: 60
    events:
      - http:
          path: author/show/{authorId}
          method: get
          cors: true
          authorizer: false
  searchAuthors:
      handler: author/author.search
      timeout: 60
      events:
        - http:
            path: author/search/{criteria}
            method: get
            cors: true
            authorizer: false
# CATEGORY SECCION
  getCategories:
    handler: category/category.get
    timeout: 60
    events:
      - http:
          path: category/all
          method: get
          cors: true
          authorizer: false
  showCategory:
    handler: category/category.show
    timeout: 60
    events:
      - http:
          path: category/show/{categoryId}
          method: get
          cors: true
          authorizer: false
  searchCategories:
      handler: category/category.search
      timeout: 60
      events:
        - http:
            path: category/search/{criteria}
            method: get
            cors: true
            authorizer: false
# USER SECCION
# ADMIN SECCION