service: serverless-article

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'test'}
  region: us-east-1
  environment:
    ENV: ${opt:stage}

functions:
  # ARTICLES SECCION
  getArticles:
    handler: article.get
    stageVariables: 
      - stage : ${opt:stage, 'test'}
    events:
      - http:
          path: article/all
          method: get
          cors:
              origin: '*'
              headers:
                - Content-Type
                - Access-Control-Allow-Headers
                - Access-Control-Allow-Origin
                - Token
              allowCredentials: false
          authorizer: false
  getArticlesByFollowingAuthors:
    handler: article.getArticlesByFollowingAuthors
    stageVariables: 
      - stage : ${opt:stage, 'test'}
    events:
      - http:
          path: article/following/authors
          method: get
          cors:
              origin: '*'
              headers:
                - Content-Type
                - Access-Control-Allow-Headers
                - Access-Control-Allow-Origin
                - Token
              allowCredentials: false
          authorizer: false
  getArticlesByFollowingCategories:
    handler: article.getArticlesByFollowingCategories
    stageVariables: 
      - stage : ${opt:stage, 'test'}
    events:
      - http:
          path: article/following/categories
          method: get
          cors:
              origin: '*'
              headers:
                - Content-Type
                - Access-Control-Allow-Headers
                - Access-Control-Allow-Origin
                - Token
              allowCredentials: false
          authorizer: false
  getArticlesByCategories:
    handler: article.getArticlesByCategories
    stageVariables: 
      - stage : ${opt:stage, 'test'}
    events:
      - http:
          path: article/each/categories
          method: get
          cors:
              origin: '*'
              headers:
                - Content-Type
                - Access-Control-Allow-Headers
                - Access-Control-Allow-Origin
                - Token
              allowCredentials: false
          authorizer: false
  getArticlesByAuthors:
    handler: article.getArticlesByAuthor
    stageVariables:
      - stage : ${opt:stage, 'test'}
    events:
      - http:
          path: article/each/authors
          method: post
          cors:
              origin: '*'
              headers:
                - Content-Type
                - Access-Control-Allow-Headers
                - Access-Control-Allow-Origin
                - Token
              allowCredentials: false
          authorizer: false
  showArticle:
    handler: article.show
    stageVariables: 
      - stage : ${opt:stage, 'test'}
    events:
      - http:
          path: article/show/{articleId}
          method: get
          cors:
              origin: '*'
              headers:
                - Content-Type
                - Access-Control-Allow-Headers
                - Access-Control-Allow-Origin
                - Token
              allowCredentials: false
          authorizer: false
  showFullArticle:
    handler: article.getFullArticle
    stageVariables: 
      - stage : ${opt:stage, 'test'}
    events:
      - http:
          path: article/showFull/{articleId}
          method: get
          cors:
              origin: '*'
              headers:
                - Content-Type
                - Access-Control-Allow-Headers
                - Access-Control-Allow-Origin
                - Token
              allowCredentials: false
          authorizer: false
  showArticleContent:
    handler: article.getArticleContent
    stageVariables: 
      - stage : ${opt:stage, 'test'}
    events:
      - http:
          path: article/content/{articleId}
          method: get
          cors:
              origin: '*'
              headers:
                - Content-Type
                - Access-Control-Allow-Headers
                - Access-Control-Allow-Origin
                - Token
              allowCredentials: false
          authorizer: false
  getByCanonical:
    handler: article.getByCanonical
    stageVariables: 
      - stage : ${opt:stage, 'test'}
    events:
      - http:
          path: article/canonical/{canonical}
          method: get
          cors:
              origin: '*'
              headers:
                - Content-Type
                - Access-Control-Allow-Headers
                - Access-Control-Allow-Origin
                - Token
              allowCredentials: false
          authorizer: false
  getArticlesByCategory:
      handler: article.getByCategory
      stageVariables: 
      - stage : ${opt:stage, 'test'}
      events:
        - http:
            path: article/category/{categoryId}
            method: get
            cors:
              origin: '*'
              headers:
                - Content-Type
                - Access-Control-Allow-Headers
                - Access-Control-Allow-Origin
                - Token
              allowCredentials: false
            authorizer: false
  getArticlesByAuthor:
      handler: article.getByAuthor
      stageVariables: 
      - stage : ${opt:stage, 'test'}
      events:
        - http:
            path: article/author/{authorId}
            method: get
            cors:
              origin: '*'
              headers:
                - Content-Type
                - Access-Control-Allow-Headers
                - Access-Control-Allow-Origin
                - Token
              allowCredentials: false
            authorizer: false
  searchArticles:
      handler: article.search
      stageVariables: 
      - stage : ${opt:stage, 'test'}
      events:
        - http:
            path: article/search/{criteria}
            method: get
            cors:
              origin: '*'
              headers:
                - Content-Type
                - Access-Control-Allow-Headers
                - Access-Control-Allow-Origin
                - Token
              allowCredentials: false
            authorizer: false